version: '2'

services:
  apache:
    container_name: scratchpads.apache
    image: naturalhistorymuseum/scratchpads.apache
    build:
      context: ./docker/apache
    restart: always
    links:
      - mysql         
    depends_on:
      - mysql
      - solr    
    ports:
      - "${SCRATCHPADS_PORT}:80"
    volumes:     
      - apache-files:/var/www/html/sites/default
    environment:
      - BASE_URL=http://127.0.0.1:${SCRATCHPADS_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=scratchpads.mysql
      - SOLR_HOSTNAME=scratchpads.solr 
      - SOLR_CORE=scratchpads2    

  mysql:
    container_name: scratchpads.mysql
    image: naturalhistorymuseum/scratchpads-mysql
    build:
      context: ./docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql              
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal  
    mem_limit: 3G       

  solr:
    container_name: scratchpads.solr
    image: naturalhistorymuseum/scratchpads-solr
    build:
      context: ./docker/solr    
    expose:
      - 8983
    volumes:
      - solr-data:/etc/opt/solr/scratchpads2/data

volumes:   
  apache-files:
  mysql-data:
  solr-data:


