version: '2'

services:
  apache:
    container_name: scratchpads.apache
    image: naturalhistorymuseum/scratchpads.apache
    build:
      context: ./docker/apache
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
      - solr
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - apache-files:/var/www/html/sites/default
    environment:
      - BASE_URL=${APACHE_BASE_URL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=scratchpads.mysql
      - SOLR_HOSTNAME=scratchpads.solr
      - SOLR_CORE=scratchpads2
      - SMTP_FROM=${APACHE_SMTP_FROM}
      - SMTP_HOST=${APACHE_SMTP_HOST}
      - SMTP_PORT=${APACHE_SMTP_PORT}
      - SMTP_USER=${APACHE_SMTP_USER}
      - SMTP_PASSWORD=${APACHE_SMTP_PASSWORD}
      - SMTP_TLS=${APACHE_SMTP_TLS}
      - SMTP_AUTH=${APACHE_SMTP_AUTH}
      - SMTP_START_TLS=${APACHE_SMTP_START_TLS}
      - VARNISH_SECRET=${VARNISH_SECRET}
      - TAVERNA_AUTH_TOKEN=${APACHE_SCRATCHPADS_TAVERNA_AUTH_TOKEN}

  mysql:
    container_name: scratchpads.mysql
    restart: always
    image: naturalhistorymuseum/scratchpads-mysql
    build:
      context: ./docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  solr:
    container_name: scratchpads.solr
    restart: always
    image: naturalhistorymuseum/scratchpads-solr
    build:
      context: ./docker/solr
    expose:
      - 8983
    volumes:
      - solr-data:/etc/opt/solr/scratchpads2/data

  varnish:
    restart: always
    container_name: scratchpads.varnish
    build:
      context: ./docker/varnish
    depends_on:
      - apache
    expose:
      - 6082
    ports:
      - "8081:${VARNISH_PORT}"
    environment:
      VARNISH_PORT: ${VARNISH_PORT}
      VARNISH_SECRET: ${VARNISH_SECRET}

volumes:
  apache-files:
  mysql-data:
  solr-data:


